title: A Thoughtful Coder
email: al3rezl@gmail.com
description: >-
  I'm Alireza Bashiri, aka al3rez on Twitter, Github and everywhere else. I run
  a solo dev agency, Devmason, and I'm about to quit and become a full-time
  indie hacker soon. I often write on Twitter, and here I share what I learn in
  between.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://athoughtfulcoder.com"
twitter_username: al3rez
github_username: al3rez
permalink: /:title/
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
